import Image from 'next/image';
import Link from 'next/link';
import { Check, CreditCard, Landmark, Smartphone } from 'lucide-react';
import { BrandLogo } from '@/components/brand';
import { CourseImage } from '@/components/course-image';
import { formatDuration, formatXof } from '@/lib/courses';
import { requireUser } from '@/lib/auth/authorization';
import { choosePaymentAction, saveProfileAction, selectCourseAction } from './actions';

const steps = ['profil', 'formation', 'paiement', 'finalisation'] as const;
const labels = ['Profil', 'Formation', 'Paiement', 'Finalisation'];

export const dynamic = 'force-dynamic';

export default async function OnboardingPage({ searchParams }: { searchParams: Promise<{ step?: string; error?: string }> }) {
  const params = await searchParams; const requested = steps.includes(params.step as never) ? params.step! : 'profil';
  const { supabase, user, profile } = await requireUser('/onboarding');
  const [{ data: fullProfile }, { data: courses }, { data: order }] = await Promise.all([
    supabase.from('profiles').select('full_name,phone,city_country,affiliate_code,terms_accepted_at').eq('id', user.id).single(),
    supabase.from('courses').select('id,slug,title,short_description,image_url,level,duration_minutes,price_xof').eq('status', 'published').order('price_xof'),
    supabase.from('orders').select('id,status,payment_method,amount_xof,course:courses(id,slug,title,image_url,level,duration_minutes,price_xof)').eq('user_id', user.id).eq('status', 'pending').order('created_at', { ascending: false }).limit(1).maybeSingle(),
  ]);
  const index = steps.indexOf(requested as typeof steps[number]); const selected = Array.isArray(order?.course) ? order.course[0] : order?.course;
  return <main className="min-h-screen bg-slate-50 pb-16"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><BrandLogo /><Link href="/dashboard" className="text-sm font-bold text-[#071b3a]">Quitter et reprendre plus tard</Link></div></header>
    <section className="mx-auto max-w-6xl px-4 py-8"><div className="grid gap-3 sm:grid-cols-4">{labels.map((label, i) => <div key={label} className={`rounded-2xl border p-3 ${i <= index ? 'border-[#d8ad46] bg-amber-50' : 'bg-white'}`}><span className="mr-2 inline-grid h-7 w-7 place-items-center rounded-full bg-[#071b3a] text-xs font-bold text-white">{i < index ? <Check className="h-4 w-4" /> : i + 1}</span><span className="font-bold">{label}</span></div>)}</div>
      {params.error ? <p className="mt-6 rounded-xl bg-red-50 p-4 font-semibold text-red-700">Vérifiez les informations puis réessayez.</p> : null}
      {requested === 'profil' && <div className="mt-8 grid overflow-hidden rounded-3xl border bg-white shadow-sm lg:grid-cols-[.8fr_1.2fr]"><div className="relative hidden min-h-[560px] lg:block"><Image src="/images/auth/auth-hero.webp" alt="Apprenant préparant son parcours" fill sizes="40vw" className="object-cover" /></div><form action={saveProfileAction} className="grid gap-5 p-6 md:p-10"><div><p className="font-bold text-[#b98722]">Étape 1</p><h1 className="text-3xl font-extrabold text-[#071b3a]">Finalisez votre profil</h1></div><label className="grid gap-1 font-semibold">Nom complet<input name="full_name" defaultValue={fullProfile?.full_name ?? profile.full_name} className="rounded-xl border p-3" required /></label><label className="grid gap-1 font-semibold">Téléphone<input name="phone" defaultValue={fullProfile?.phone ?? ''} className="rounded-xl border p-3" required /></label><label className="grid gap-1 font-semibold">Ville ou pays<input name="city_country" defaultValue={fullProfile?.city_country ?? ''} className="rounded-xl border p-3" required /></label><label className="grid gap-1 font-semibold">Code affilié <span className="text-xs font-normal text-slate-500">facultatif</span><input name="affiliate_code" defaultValue={fullProfile?.affiliate_code ?? ''} className="rounded-xl border p-3" /></label><label className="flex gap-3 text-sm"><input name="terms" type="checkbox" defaultChecked={Boolean(fullProfile?.terms_accepted_at)} required />J’accepte les conditions d’utilisation.</label><button className="rounded-xl bg-[#d8ad46] px-5 py-3 font-extrabold">Continuer vers les formations</button></form></div>}
      {requested === 'formation' && <section className="mt-8"><h1 className="text-3xl font-extrabold text-[#071b3a]">Choisissez votre formation</h1><div className="mt-6 grid gap-6 md:grid-cols-3">{(courses ?? []).map(course => <article key={course.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm"><CourseImage {...course} className="aspect-video" /><div className="p-5"><p className="text-sm font-bold text-[#b98722]">{course.level} · {formatDuration(course.duration_minutes)}</p><h2 className="mt-2 text-xl font-extrabold">{course.title}</h2><p className="mt-2 text-sm text-slate-600">{course.short_description}</p><p className="mt-4 font-extrabold">{formatXof(course.price_xof)}</p><form action={selectCourseAction} className="mt-4"><input type="hidden" name="course_id" value={course.id} /><button className="w-full rounded-xl bg-[#071b3a] px-4 py-3 font-bold text-white">Sélectionner</button></form></div></article>)}</div></section>}
      {requested === 'paiement' && <section className="mx-auto mt-8 max-w-3xl rounded-3xl border bg-white p-6 shadow-sm md:p-10"><h1 className="text-3xl font-extrabold">Choisissez un moyen de paiement</h1><p className="mt-2 text-slate-600">Aucun débit n’est effectué dans cette version de démonstration. La demande restera en attente de validation administrative.</p><form action={choosePaymentAction} className="mt-6 grid gap-4">{[['mobile_money','Mobile Money',Smartphone],['card','Carte bancaire',CreditCard],['manual_validation','Validation administrative',Landmark]].map(([value,label,Icon]) => { const PaymentIcon=Icon as typeof Smartphone; return <label key={String(value)} className="flex cursor-pointer items-center gap-4 rounded-2xl border p-4 hover:border-[#d8ad46]"><input type="radio" name="payment_method" value={String(value)} required defaultChecked={order?.payment_method === value} /><PaymentIcon className="h-6 w-6 text-[#b98722]" /><span className="font-bold">{String(label)}</span></label>})}<button className="mt-2 rounded-xl bg-[#d8ad46] px-5 py-3 font-extrabold">Enregistrer mon choix</button></form></section>}
      {requested === 'finalisation' && <section className="mx-auto mt-8 max-w-3xl rounded-3xl border bg-white p-6 shadow-sm md:p-10"><p className="font-bold text-[#b98722]">Demande enregistrée</p><h1 className="mt-2 text-3xl font-extrabold">Votre parcours est prêt</h1>{selected && <div className="mt-6 grid gap-5 sm:grid-cols-[180px_1fr]"><CourseImage slug={selected.slug} title={selected.title} imageUrl={selected.image_url} className="aspect-video rounded-2xl" /><div><h2 className="text-xl font-bold">{selected.title}</h2><p className="mt-2">Mode : <strong>{order?.payment_method?.replaceAll('_', ' ')}</strong></p><p className="mt-1">Statut : <strong className="text-amber-700">En attente de validation</strong></p></div></div>}<p className="mt-6 rounded-2xl bg-amber-50 p-4 text-amber-950">L’administration vérifiera votre demande. Aucun paiement accepté et aucune inscription automatique n’ont été créés.</p><Link href="/dashboard" className="mt-6 inline-flex rounded-xl bg-[#071b3a] px-6 py-3 font-bold text-white">Accéder à mon espace</Link></section>}
    </section>
  </main>;
}
