import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Clock, Eye, GraduationCap, Lock, Target, Users } from 'lucide-react';
import { PublicHeader, SiteFooter } from '@/components/brand';
import { CourseImage } from '@/components/course-image';
import { formatDuration, formatXof, getPublishedCourse } from '@/lib/courses';

export const dynamic = 'force-dynamic';
export default async function FormationDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const course = await getPublishedCourse(slug); if (!course) notFound();
  const modules = course.modules.toSorted((a,b) => a.position-b.position); const lessons = modules.flatMap(module => module.lessons);
  const totalMinutes = lessons.reduce((sum, lesson) => sum + lesson.duration_minutes, 0);
  const moduleLabel = `${modules.length} module${modules.length > 1 ? 's' : ''}`; const lessonLabel = `${lessons.length} leçon${lessons.length > 1 ? 's' : ''}`;
  return <main className="min-h-screen bg-white"><PublicHeader active="formations" />
    <section className="evr-navy-panel text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 lg:grid-cols-2"><CourseImage slug={course.slug} title={course.title} imageUrl={course.image_url} className="aspect-video rounded-3xl"/><div><p className="text-[#f5df99]">Formation professionnelle</p><h1 className="mt-3 text-4xl font-extrabold md:text-5xl">{course.title}</h1><p className="mt-5 text-lg text-slate-200">{course.description}</p><div className="mt-6 flex flex-wrap gap-4 text-sm"><span className="flex gap-2"><GraduationCap/> {course.level}</span><span className="flex gap-2"><Clock/> {formatDuration(totalMinutes || course.duration_minutes)}</span><strong className="text-[#f5df99]">{formatXof(course.price_xof)}</strong></div><Link href={`/onboarding?step=formation`} className="mt-8 inline-flex rounded-full bg-amber-400 px-6 py-3 font-extrabold text-[#071b3a]">Choisir cette formation</Link></div></div></section>
    <nav aria-label="Sections de la formation" className="sticky top-[77px] z-20 border-b bg-white"><div className="mx-auto flex max-w-5xl gap-6 overflow-x-auto px-4 py-4 font-bold"><a href="#apercu">Aperçu</a><a href="#programme">Programme</a><a href="#formateurs">Formateurs</a><a href="#informations">Informations pratiques</a></div></nav>
    <section id="apercu" className="mx-auto grid max-w-5xl gap-8 px-4 py-12 md:grid-cols-2"><div><p className="font-bold text-[#b98722]">Aperçu</p><h2 className="mt-2 text-3xl font-extrabold">Des compétences directement applicables</h2><p className="mt-4 leading-7 text-slate-600">{course.description}</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><Target className="text-[#b98722]"/><h3 className="mt-3 font-bold">Objectifs</h3><p className="mt-2 text-sm text-slate-600">Structurer vos entretiens, convaincre et fidéliser durablement.</p></div><div className="rounded-2xl bg-slate-50 p-5"><Users className="text-[#b98722]"/><h3 className="mt-3 font-bold">Public cible</h3><p className="mt-2 text-sm text-slate-600">Vendeurs, commerciaux terrain et responsables d’équipe.</p></div></div></section>
    <section id="programme" className="bg-slate-50"><div className="mx-auto max-w-5xl px-4 py-12"><p className="font-bold text-[#b98722]">Table des matières</p><h2 className="mt-2 text-3xl font-extrabold text-[#071b3a]">Programme · {moduleLabel} · {lessonLabel}</h2><p className="mt-2 text-slate-600">Durée pédagogique : {formatDuration(totalMinutes)}</p><div className="mt-6 space-y-4">{modules.map(module=><details key={module.id} open={module.position===1} className="rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold text-[#071b3a]">Module {module.position} · {module.title} <span className="font-normal text-slate-500">({module.lessons.length} leçon{module.lessons.length>1?'s':''})</span></summary><p className="mt-2 text-sm text-slate-600">{module.description}</p><div className="mt-4 space-y-2">{module.lessons.toSorted((a,b)=>a.position-b.position).map(lesson=><div key={lesson.id} className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-3"><div><p className="font-semibold">{lesson.title}</p><p className="text-xs text-slate-500">{formatDuration(lesson.duration_minutes)}</p></div>{lesson.is_preview ? <Link href={`/cours/${course.slug}?lesson=${lesson.slug}`} className="flex items-center gap-1 font-bold text-blue-700"><Eye className="h-4 w-4"/> Aperçu</Link>:<span className="flex items-center gap-1 text-xs text-slate-500"><Lock className="h-4 w-4"/> Verrouillée</span>}</div>)}</div></details>)}</div></div></section>
    <section id="formateurs" className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-3xl font-extrabold">Équipe pédagogique</h2><div className="mt-6 grid gap-6 sm:grid-cols-3">{['Expert vente terrain','Coach performance commerciale','Responsable pédagogique'].map((role,index)=><article key={role} className="overflow-hidden rounded-3xl border bg-white"><div className="relative aspect-[4/5]"><Image src={`/images/formateurs/formateur-${index+1}.webp`} alt={`Membre de l’équipe pédagogique — ${role}`} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover" /></div><div className="p-5"><h3 className="font-extrabold">Équipe École des Vendeurs</h3><p className="mt-1 text-sm text-[#b98722]">{role}</p><p className="mt-2 text-sm text-slate-600">Accompagnement pratique, retours d’expérience et mises en situation.</p></div></article>)}</div></section>
    <section id="informations" className="mx-auto max-w-5xl px-4 pb-14"><div className="rounded-3xl bg-[#071b3a] p-8 text-white"><h2 className="text-2xl font-extrabold">Informations pratiques</h2><p className="mt-3 text-slate-200">Formation en ligne, accessible à votre rythme après validation de l’inscription. Prérequis : disposer d’un téléphone ou ordinateur connecté.</p></div></section><SiteFooter />
  </main>;
}
