import Link from 'next/link';
import { notFound } from 'next/navigation';
import { CheckCircle2, Circle, Lock, Play } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import { updateLessonProgress } from './actions';

export const dynamic='force-dynamic';
export default async function CoursePlayer({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{lesson?:string}>}){
  const [{slug},{lesson:requested}]=await Promise.all([params,searchParams]); const supabase=await createClient();
  const [{data:{user}},{data:course}]=await Promise.all([supabase.auth.getUser(),supabase.from('courses').select('id,slug,title,status,modules(id,title,position,lessons(id,slug,title,objective,content,exercise,duration_minutes,position,is_preview))').eq('slug',slug).eq('status','published').maybeSingle()]);
  if(!course) notFound();
  const modules=(course.modules??[]).toSorted((a,b)=>a.position-b.position).map(m=>({...m,lessons:(m.lessons??[]).toSorted((a,b)=>a.position-b.position)}));
  const lessons=modules.flatMap(m=>m.lessons); const lesson=lessons.find(l=>l.slug===requested)??lessons[0]; if(!lesson) notFound();
  const {data:progress}=user?await supabase.from('lesson_progress').select('lesson_id,completed').eq('profile_id',user.id):{data:[]};
  const done=new Set((progress??[]).filter(p=>p.completed).map(p=>p.lesson_id)); const index=lessons.findIndex(l=>l.id===lesson.id); const previous=lessons[index-1]; const next=lessons[index+1];
  return <main className="grid min-h-screen bg-slate-50 lg:grid-cols-[320px_1fr]"><aside className="bg-[#071b3a] p-5 text-white"><Link href={`/formations/${slug}`} className="text-sm text-[#f5df99]">← Retour à la formation</Link><h1 className="mt-4 text-xl font-extrabold">{course.title}</h1><div className="mt-7 space-y-6">{modules.map(m=><section key={m.id}><h2 className="font-bold">{m.position}. {m.title}</h2><div className="mt-2 space-y-1">{m.lessons.map(l=><Link key={l.id} href={`/cours/${slug}?lesson=${l.slug}`} className={`flex items-center gap-2 rounded-xl p-3 text-sm ${l.id===lesson.id?'bg-white text-[#071b3a]':'text-slate-300 hover:bg-white/10'}`}>{done.has(l.id)?<CheckCircle2 className="h-4 w-4 text-green-500"/>:l.is_preview?<Play className="h-4 w-4"/>:<Lock className="h-4 w-4"/>}{l.title}</Link>)}</div></section>)}</div></aside><section><header className="border-b bg-white px-6 py-4"><p className="text-sm font-bold text-[#b98722]">{lesson.is_preview?'Aperçu public':'Leçon réservée aux inscrits'}</p></header><article className="mx-auto max-w-4xl px-5 py-10"><h2 className="text-4xl font-extrabold text-[#071b3a]">{lesson.title}</h2><p className="mt-4 rounded-2xl bg-blue-50 p-5 font-semibold text-blue-950">Objectif : {lesson.objective}</p><div className="mt-7 whitespace-pre-line text-lg leading-8 text-slate-700">{lesson.content}</div>{lesson.exercise&&<div className="mt-8 rounded-3xl border border-amber-200 bg-amber-50 p-6"><h3 className="font-extrabold text-amber-950">Mise en application</h3><p className="mt-2 text-amber-900">{lesson.exercise}</p></div>}{user&&<form action={updateLessonProgress} className="mt-8"><input type="hidden" name="lessonId" value={lesson.id}/><input type="hidden" name="courseSlug" value={slug}/><input type="hidden" name="completed" value={done.has(lesson.id)?'false':'true'}/><button className="flex items-center gap-2 rounded-xl bg-green-700 px-5 py-3 font-bold text-white">{done.has(lesson.id)?<Circle className="h-5 w-5"/>:<CheckCircle2 className="h-5 w-5"/>}{done.has(lesson.id)?'Marquer à reprendre':'Marquer comme terminée'}</button></form>}<nav className="mt-10 grid gap-3 sm:grid-cols-2">{previous?<Link href={`/cours/${slug}?lesson=${previous.slug}`} className="rounded-xl border bg-white px-5 py-4 font-bold">← {previous.title}</Link>:<span/>}{next&&<Link href={`/cours/${slug}?lesson=${next.slug}`} className="rounded-xl bg-blue-700 px-5 py-4 text-right font-bold text-white">{next.title} →</Link>}</nav></article></section></main>;
}
