'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { z } from 'zod';
import { requireAdmin } from '@/lib/auth/authorization';

const text=z.string().trim().min(2).max(5000);
const courseSchema=z.object({id:z.string().uuid().optional(),title:text.max(160),slug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),short_description:text.max(300),description:text,level:z.enum(['Débutant','Intermédiaire','Avancé']),price_xof:z.coerce.number().int().min(0),duration_minutes:z.coerce.number().int().min(0),status:z.enum(['draft','published','archived'])});
export async function saveCourse(formData:FormData){const input=courseSchema.parse(Object.fromEntries(formData));const {supabase,user}=await requireAdmin('/admin/formations');const payload={title:input.title,slug:input.slug,short_description:input.short_description,description:input.description,level:input.level,price_xof:input.price_xof,duration_minutes:input.duration_minutes,status:input.status,created_by:user.id};let id=input.id;if(id){const {error}=await supabase.from('courses').update(payload).eq('id',id);if(error)throw new Error('Formation non modifiée.');}else{const {data,error}=await supabase.from('courses').insert(payload).select('id').single();if(error)throw new Error('Formation non créée.');id=data.id;}revalidatePath('/');revalidatePath('/formations');redirect(`/admin/formations/${id}/modifier?success=1`);}

const moduleSchema=z.object({course_id:z.string().uuid(),module_id:z.string().uuid().optional(),title:text.max(180),description:z.string().trim().max(1000),position:z.coerce.number().int().min(1)});
export async function saveModule(formData:FormData){const input=moduleSchema.parse(Object.fromEntries(formData));const {supabase}=await requireAdmin(`/admin/formations/${input.course_id}/modules`);const payload={course_id:input.course_id,title:input.title,description:input.description,position:input.position};const query=input.module_id?supabase.from('modules').update(payload).eq('id',input.module_id):supabase.from('modules').insert(payload);const {error}=await query;if(error)throw new Error('Module non enregistré.');revalidatePath(`/admin/formations/${input.course_id}/modules`);}
export async function deleteModule(formData:FormData){const input=z.object({course_id:z.string().uuid(),module_id:z.string().uuid()}).parse(Object.fromEntries(formData));const {supabase}=await requireAdmin(`/admin/formations/${input.course_id}/modules`);const {count}=await supabase.from('lessons').select('id',{count:'exact',head:true}).eq('module_id',input.module_id);if(count)throw new Error('Supprimez les leçons avant ce module.');const {error}=await supabase.from('modules').delete().eq('id',input.module_id);if(error)throw new Error('Module non supprimé.');revalidatePath(`/admin/formations/${input.course_id}/modules`);}

const lessonSchema=z.object({course_id:z.string().uuid(),module_id:z.string().uuid(),lesson_id:z.string().uuid().optional(),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),title:text.max(180),objective:text.max(1000),content:text,exercise:z.string().trim().max(3000),duration_minutes:z.coerce.number().int().min(0),position:z.coerce.number().int().min(1),is_preview:z.string().optional()});
export async function saveLesson(formData:FormData){const input=lessonSchema.parse(Object.fromEntries(formData));const {supabase}=await requireAdmin(`/admin/formations/${input.course_id}/modules`);const payload={module_id:input.module_id,slug:input.slug,title:input.title,objective:input.objective,content:input.content,exercise:input.exercise,duration_minutes:input.duration_minutes,position:input.position,is_preview:input.is_preview==='on'};const query=input.lesson_id?supabase.from('lessons').update(payload).eq('id',input.lesson_id):supabase.from('lessons').insert(payload);const {error}=await query;if(error)throw new Error('Leçon non enregistrée.');revalidatePath(`/admin/formations/${input.course_id}/modules`);}
export async function deleteLesson(formData:FormData){const input=z.object({course_id:z.string().uuid(),lesson_id:z.string().uuid()}).parse(Object.fromEntries(formData));const {supabase}=await requireAdmin(`/admin/formations/${input.course_id}/modules`);const {error}=await supabase.from('lessons').delete().eq('id',input.lesson_id);if(error)throw new Error('Leçon non supprimée.');revalidatePath(`/admin/formations/${input.course_id}/modules`);}

export async function setUserStatus(formData:FormData){const input=z.object({profile_id:z.string().uuid(),active:z.enum(['true','false'])}).parse(Object.fromEntries(formData));const {supabase}=await requireAdmin('/admin/utilisateurs');const {error}=await supabase.rpc('set_profile_status',{target_profile_id:input.profile_id,target_active:input.active==='true'});if(error)throw new Error('Statut non modifié.');revalidatePath('/admin/utilisateurs');}
export async function saveEnrollment(formData:FormData){const input=z.object({profile_id:z.string().uuid(),course_id:z.string().uuid()}).parse(Object.fromEntries(formData));const {supabase}=await requireAdmin('/admin/inscriptions');const {error}=await supabase.from('enrollments').upsert({user_id:input.profile_id,course_id:input.course_id,active:true,enrolled_at:new Date().toISOString()},{onConflict:'user_id,course_id'});if(error)throw new Error('Inscription non enregistrée.');revalidatePath('/admin/inscriptions');}
export async function deactivateEnrollment(formData:FormData){const id=z.string().uuid().parse(formData.get('id'));const {supabase}=await requireAdmin('/admin/inscriptions');const {error}=await supabase.from('enrollments').update({active:false}).eq('id',id);if(error)throw new Error('Inscription non désactivée.');revalidatePath('/admin/inscriptions');}
