import Link from 'next/link';
import { BookOpen, CreditCard, GraduationCap, Mail, Users } from 'lucide-react';
import { AdminShell } from '@/components/admin-nav';
import { MetricCard } from '@/components/brand';
import { requireAdmin } from '@/lib/auth/authorization';

export const dynamic='force-dynamic';
export default async function AdminDashboard(){
  const {supabase}=await requireAdmin('/admin');
  const [courses,published,drafts,learners,enrollments,recentCourses,recentEnrollments,progress,messages,pendingPayments]=await Promise.all([
    supabase.from('courses').select('*',{count:'exact',head:true}),supabase.from('courses').select('*',{count:'exact',head:true}).eq('status','published'),supabase.from('courses').select('*',{count:'exact',head:true}).eq('status','draft'),supabase.from('profiles').select('*',{count:'exact',head:true}).eq('role','apprenant'),supabase.from('enrollments').select('*',{count:'exact',head:true}).eq('active',true),supabase.from('courses').select('id,title,status,updated_at').order('updated_at',{ascending:false}).limit(5),supabase.from('enrollments').select('id,enrolled_at,profile:profiles(full_name,email),course:courses(title)').order('enrolled_at',{ascending:false}).limit(5),supabase.from('lesson_progress').select('completed'),supabase.from('contact_messages').select('*',{count:'exact',head:true}).eq('status','new'),supabase.from('orders').select('*',{count:'exact',head:true}).eq('status','pending')
  ]);
  const values=progress.data??[];const average=values.length?Math.round(values.filter(item=>item.completed).length/values.length*100):0;
  const latest=(recentEnrollments.data??[]).map(item=>({...item,profile:Array.isArray(item.profile)?item.profile[0]:item.profile,course:Array.isArray(item.course)?item.course[0]:item.course}));
  const quickActions=[['Créer une formation','/admin/formations/nouvelle'],['Ajouter une leçon','/admin/formations'],['Inscrire un apprenant','/admin/inscriptions'],['Consulter les messages','/admin/messages'],['Consulter les utilisateurs','/admin/utilisateurs'],['Voir le site public','/']] as const;
  return <AdminShell>
    <div className="flex justify-between gap-4"><div><p className="font-bold text-[#b98722]">Administration</p><h1 className="text-4xl font-extrabold text-[#071b3a]">Tableau de bord</h1></div><Link href="/admin/formations/nouvelle" className="h-fit rounded-xl bg-green-700 px-5 py-3 font-bold text-white">Créer une formation</Link></div>
    <div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Formations" value={String(courses.count??0)} icon={<BookOpen/>}/><MetricCard label="Publiées" value={String(published.count??0)} tone="green"/><MetricCard label="Brouillons" value={String(drafts.count??0)} tone="gold"/><MetricCard label="Apprenants" value={String(learners.count??0)} icon={<Users/>}/><MetricCard label="Inscriptions actives" value={String(enrollments.count??0)} icon={<GraduationCap/>}/><MetricCard label="Progression moyenne" value={`${average}%`} tone="green"/><MetricCard label="Messages nouveaux" value={String(messages.count??0)} tone="gold" icon={<Mail/>}/><MetricCard label="Paiements en attente" value={String(pendingPayments.count??0)} tone="gold" icon={<CreditCard/>}/></div>
    <section className="mt-8 rounded-3xl border bg-white p-6"><h2 className="text-xl font-extrabold">Actions rapides</h2><div className="mt-4 flex flex-wrap gap-3">{quickActions.map(([label,href],index)=><Link key={href} href={href} className={index===0?'rounded-xl bg-[#071b3a] px-4 py-3 font-bold text-white':'rounded-xl border px-4 py-3 font-bold'}>{label}</Link>)}</div></section>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-extrabold">Dernières formations modifiées</h2><div className="mt-4 divide-y">{(recentCourses.data??[]).map(course=><p key={course.id} className="flex justify-between py-3"><span>{course.title}</span><span className="text-sm text-slate-500">{course.status}</span></p>)}</div></section><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-extrabold">Dernières inscriptions</h2><div className="mt-4 divide-y">{latest.map(item=><p key={item.id} className="py-3"><strong>{item.profile?.full_name||item.profile?.email}</strong><span className="block text-sm text-slate-500">{item.course?.title}</span></p>)}</div></section></div>
  </AdminShell>;
}
