import Link from 'next/link';
import { ArrowRight, BookOpen, CheckCircle2, Clock3, ListChecks, PlayCircle } from 'lucide-react';
import { CourseImage } from '@/components/course-image';
import { LearnerShell } from '@/components/learner-shell';
import { WelcomeToast } from '@/components/welcome-toast';
import { requireUser } from '@/lib/auth/authorization';
import { shouldShowFirstLoginWelcome } from '@/lib/auth/welcome';

export const dynamic='force-dynamic';
export default async function DashboardPage(){
  const {supabase,user,profile}=await requireUser('/dashboard');
  const [{data:fullProfile},{data:enrollments,error},{data:pendingOrder}]=await Promise.all([
    supabase.from('profiles').select('full_name,phone,city_country,terms_accepted_at,first_login_welcome_seen_at').eq('id',user.id).single(),
    supabase.from('enrollments').select('id,active,enrolled_at,course:courses(id,slug,title,short_description,image_url,duration_minutes,modules(id,title,position,lessons(id,slug,title,duration_minutes,position)))').eq('user_id',user.id).eq('active',true).order('enrolled_at',{ascending:false}),
    supabase.from('orders').select('id,status,payment_method,course:courses(id,slug,title,short_description,image_url,level,duration_minutes,price_xof)').eq('user_id',user.id).eq('status','pending').order('created_at',{ascending:false}).limit(1).maybeSingle(),
  ]);
  if(error) throw new Error('Impossible de charger vos inscriptions.');
  const name=fullProfile?.full_name||profile.full_name||user.email||'Apprenant'; const profileComplete=Boolean(fullProfile?.full_name&&fullProfile.phone&&fullProfile.city_country&&fullProfile.terms_accepted_at);
  const normalized=(enrollments??[]).map(item=>({...item,course:Array.isArray(item.course)?item.course[0]:item.course}));
  const lessonIds=normalized.flatMap(item=>item.course?.modules??[]).flatMap(module=>module.lessons??[]).map(lesson=>lesson.id);
  const {data:progress}=lessonIds.length?await supabase.from('lesson_progress').select('lesson_id,completed,last_viewed_at').eq('profile_id',user.id).in('lesson_id',lessonIds):{data:[]};
  const progressMap=new Map((progress??[]).map(item=>[item.lesson_id,item])); const pendingCourse=Array.isArray(pendingOrder?.course)?pendingOrder.course[0]:pendingOrder?.course;
  const onboardingComplete=profileComplete&&(normalized.length>0||Boolean(pendingCourse)); const showFirstWelcome=shouldShowFirstLoginWelcome({role:profile.role,onboardingComplete,seenAt:fullProfile?.first_login_welcome_seen_at??null});
  return <LearnerShell name={name}>{showFirstWelcome&&<WelcomeToast/>}<header className="border-b bg-white px-5 py-6 md:px-10"><p className="font-bold text-[#b98722]">Espace apprenant</p><h1 className="mt-1 text-3xl font-extrabold text-[#071b3a]">Bonjour, {name}</h1></header><section className="mx-auto max-w-6xl px-5 py-8 md:px-10">
    {!onboardingComplete&&!showFirstWelcome&&<div className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><p className="font-bold text-amber-800">Votre inscription n’est pas encore terminée</p><h2 className="mt-2 text-2xl font-extrabold">Reprenez les étapes de finalisation</h2><p className="mt-2 text-sm text-slate-600">Complétez votre profil, choisissez une formation puis enregistrez votre mode de validation.</p><Link href="/onboarding" className="mt-5 inline-flex rounded-xl bg-[#071b3a] px-5 py-3 font-bold text-white">Reprendre la finalisation</Link></div>}
    {profileComplete&&normalized.length===0&&pendingCourse&&<div className="overflow-hidden rounded-3xl border bg-white shadow-sm md:grid md:grid-cols-[320px_1fr]"><CourseImage slug={pendingCourse.slug} title={pendingCourse.title} imageUrl={pendingCourse.image_url} className="aspect-video md:aspect-auto"/><div className="p-7"><p className="font-bold text-amber-700">Validation en attente</p><h2 className="mt-2 text-2xl font-extrabold">{pendingCourse.title}</h2><p className="mt-3 text-slate-600">Votre choix est enregistré. L’administration doit encore valider l’inscription. Aucun débit ni paiement accepté n’a été simulé.</p><p className="mt-4 text-sm">Moyen choisi : <strong>{pendingOrder?.payment_method?.replaceAll('_',' ')}</strong></p><Link href="/onboarding?step=finalisation" className="mt-5 inline-flex rounded-xl border px-5 py-3 font-bold">Voir ma demande</Link></div></div>}
    {profileComplete&&normalized.length===0&&!pendingCourse&&<div className="rounded-3xl border bg-white p-10 text-center"><BookOpen className="mx-auto h-10 w-10 text-[#b98722]"/><h2 className="mt-4 text-2xl font-extrabold">Choisissez votre première formation</h2><p className="mt-2 text-slate-600">Trois parcours sont disponibles, sans fausse progression.</p><Link href="/onboarding?step=formation" className="mt-5 inline-flex rounded-xl bg-[#d8ad46] px-5 py-3 font-bold">Choisir une formation</Link></div>}
    {normalized.length>0&&<div id="mes-cours" className="grid gap-6">{normalized.map(enrollment=>{const course=enrollment.course!;const lessons=course.modules.toSorted((a,b)=>a.position-b.position).flatMap(module=>module.lessons.toSorted((a,b)=>a.position-b.position));const completed=lessons.filter(lesson=>progressMap.get(lesson.id)?.completed).length;const percent=lessons.length?Math.round(completed/lessons.length*100):0;const last=[...lessons].sort((a,b)=>new Date(progressMap.get(b.id)?.last_viewed_at??0).getTime()-new Date(progressMap.get(a.id)?.last_viewed_at??0).getTime()).find(lesson=>progressMap.has(lesson.id));const next=lessons.find(lesson=>!progressMap.get(lesson.id)?.completed)??lessons.at(-1);const remaining=lessons.filter(lesson=>!progressMap.get(lesson.id)?.completed).reduce((sum,lesson)=>sum+lesson.duration_minutes,0);return <article key={enrollment.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="grid lg:grid-cols-[380px_1fr]"><CourseImage slug={course.slug} title={course.title} imageUrl={course.image_url} className="aspect-video lg:aspect-auto"/><div className="p-6 md:p-8"><p className="font-bold text-[#b98722]">Formation en cours</p><h2 className="mt-2 text-3xl font-extrabold">{course.title}</h2><div id="progression" className="mt-6 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-green-600" style={{width:`${percent}%`}}/></div><div className="mt-2 flex justify-between text-sm font-bold"><span>{completed}/{lessons.length} leçons terminées</span><span>{percent}%</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><ListChecks className="h-5 w-5 text-[#b98722]"/><p className="mt-2 text-sm">Modules</p><strong>{course.modules.length}</strong></div><div className="rounded-2xl bg-slate-50 p-4"><Clock3 className="h-5 w-5 text-[#b98722]"/><p className="mt-2 text-sm">Temps restant</p><strong>{Math.ceil(remaining/60)} h</strong></div><div className="rounded-2xl bg-slate-50 p-4"><CheckCircle2 className="h-5 w-5 text-[#b98722]"/><p className="mt-2 text-sm">Progression</p><strong>{percent}%</strong></div></div><p className="mt-5 text-sm text-slate-600">{last?`Dernière leçon : ${last.title}`:'Commencez votre première leçon.'}</p>{next&&<Link href={`/cours/${course.slug}?lesson=${next.slug}`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#071b3a] px-5 py-3 font-bold text-white"><PlayCircle className="h-5 w-5"/>Continuer le cours<ArrowRight className="h-4 w-4"/></Link>}</div></div></article>})}</div>}
  </section></LearnerShell>;
}
