import Image from 'next/image';
import Link from 'next/link';
import { BookOpenCheck, Compass, Goal, Handshake, Target } from 'lucide-react';
import { PublicHeader, SiteFooter } from '@/components/brand';

export const metadata = { title: 'À propos | École des Vendeurs de Race' };
const pillars=[[Goal,'Notre mission','Rendre le développement des compétences commerciales plus structuré, progressif et directement applicable.'],[Compass,'Notre vision','Proposer un environnement d’apprentissage clair, adapté aux réalités quotidiennes de la vente.'],[BookOpenCheck,'Notre méthode','Des objectifs explicites, des leçons courtes, des exercices et une progression visible.']] as const;

export default function AboutPage(){return <main className="min-h-screen bg-white"><PublicHeader active="about"/><section className="evr-navy-panel text-white"><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-16 lg:grid-cols-2"><div><p className="font-bold uppercase tracking-[.2em] text-[#f5df99]">À propos de nous</p><h1 className="mt-4 text-4xl font-black md:text-5xl">Une plateforme dédiée aux compétences commerciales.</h1><p className="mt-5 text-lg leading-8 text-slate-200">L’École des Vendeurs de Race organise des contenus pratiques pour accompagner les apprenants, du socle de la vente jusqu’au pilotage de la performance.</p></div><div className="relative min-h-80 overflow-hidden rounded-3xl"><Image src="/images/formations/vente-terrain.webp" alt="Professionnels échangeant autour de pratiques de vente" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div></div></section><section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-6 md:grid-cols-3">{pillars.map(([Icon,title,text])=><article key={title} className="rounded-3xl border bg-slate-50 p-7"><Icon className="h-8 w-8 text-[#b98722]"/><h2 className="mt-4 text-2xl font-extrabold">{title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div><div className="mt-16 grid gap-10 lg:grid-cols-2"><div><p className="font-bold text-[#b98722]">Pour qui ?</p><h2 className="mt-2 text-3xl font-extrabold">Des parcours conçus pour progresser sur le terrain</h2><p className="mt-5 leading-7 text-slate-600">Les formations s’adressent aux personnes qui débutent dans la vente, aux commerciaux souhaitant consolider leurs pratiques et aux responsables qui veulent mieux piloter leur activité.</p><div className="mt-6 grid gap-3"><p className="flex gap-3"><Target className="text-green-700"/>Prospection, découverte et argumentation</p><p className="flex gap-3"><Handshake className="text-green-700"/>Négociation, suivi client et fidélisation</p><p className="flex gap-3"><BookOpenCheck className="text-green-700"/>Organisation, objectifs et mise en pratique</p></div></div><div className="rounded-3xl bg-[#071b3a] p-8 text-white"><h2 className="text-3xl font-extrabold">Commencez par le parcours adapté à votre niveau.</h2><p className="mt-4 text-slate-300">Consultez le programme complet de chaque formation avant de créer votre compte.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/formations" className="rounded-full bg-[#d8ad46] px-5 py-3 font-bold text-[#071b3a]">Voir les formations</Link><Link href="/contact" className="rounded-full border border-white/30 px-5 py-3 font-bold">Nous contacter</Link></div></div></div></section><SiteFooter/></main>}
