import { AdminShell } from '@/components/admin-nav';
import { deactivateEnrollment, saveEnrollment } from '@/app/(dashboard)/admin/actions';
import { requireAdmin } from '@/lib/auth/authorization';
export const dynamic='force-dynamic';
export default async function Enrollments(){
 const {supabase}=await requireAdmin('/admin/inscriptions');
 const [{data:profiles},{data:courses},{data:enrollments,error}]=await Promise.all([supabase.from('profiles').select('id,email,full_name').eq('status','active').order('full_name'),supabase.from('courses').select('id,title').neq('status','archived').order('title'),supabase.from('enrollments').select('id,active,enrolled_at,profile:profiles(id,email,full_name),course:courses(id,title)').order('enrolled_at',{ascending:false})]);
 if(error)throw new Error('Inscriptions indisponibles.');
 const rows=(enrollments??[]).map(e=>({...e,profile:Array.isArray(e.profile)?e.profile[0]:e.profile,course:Array.isArray(e.course)?e.course[0]:e.course}));
 return <AdminShell><h1 className="text-4xl font-extrabold text-[#071b3a]">Inscriptions</h1><form action={saveEnrollment} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 sm:grid-cols-[1fr_1fr_auto]"><select required name="profile_id" className="rounded-xl border px-3"><option value="">Choisir un apprenant</option>{(profiles??[]).map(p=><option key={p.id} value={p.id}>{p.full_name||p.email}</option>)}</select><select required name="course_id" className="rounded-xl border px-3"><option value="">Choisir une formation</option>{(courses??[]).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button className="rounded-xl bg-green-700 px-5 py-3 font-bold text-white">Inscrire</button></form><div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[700px] text-left"><thead><tr><th className="p-4">Apprenant</th><th className="p-4">Formation</th><th className="p-4">Statut</th><th className="p-4">Action</th></tr></thead><tbody>{rows.map(e=><tr key={e.id} className="border-t"><td className="p-4">{e.profile?.full_name||e.profile?.email}</td><td className="p-4">{e.course?.title}</td><td className="p-4">{e.active?'Active':'Inactive'}</td><td className="p-4">{e.active&&<form action={deactivateEnrollment}><input type="hidden" name="id" value={e.id}/><button className="font-bold text-red-700">Désactiver</button></form>}</td></tr>)}</tbody></table></div></AdminShell>;
}
